name: parlminutes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=22.0.4
  - pandas>=2.0.0
  - numpy>=1.20.0
  - scikit-learn>=1.0.0
  - scipy>=1.8.0
  - requests>=2.28.0
  - fastapi>=0.95.0
  - uvicorn>=0.20.0
  - streamlit>=1.22.0
  - matplotlib>=3.5.0
  - plotly>=5.10.0
  - networkx>=2.8.0
  - pip:
    - sentence-transformers>=2.2.0
    - qdrant-client>=1.5.0
    - python-louvain>=0.16
    - spacy>=3.5.0
    - textblob>=0.17.1
    - torch>=2.0.0 